backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/src/media" # Media files will be stored in the repo under images/uploads

collections:
  - name: "indeed-clone"
    label: "vacancies"
    folder: "src/vacancies"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: "post"}
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Salary", name: "salary", widget: "string" }
      - { label: "Shift", name: "shift", widget: "string" }
      - { label: "Desc1", name: "desc1", widget: "string" }
      - { label: "Desc2", name: "desc2", widget: "string" }