backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "/src/media" # Media files will be stored in the repo under images/uploads

collections:
  - name: "indeed-clone"
    label: "Indeed-clone"
    folder: "src/vacancies"
    create: true
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "string" }
      - { label: "company", name: "title", widget: "string" }
      - { label: "tags", name: "title", widget: "string" }
      - { label: "location", name: "title", widget: "string" }
      - { label: "salary", name: "title", widget: "string" }
      - { label: "shift", name: "title", widget: "string" }
      - { label: "desc1", name: "title", widget: "string" }
      - { label: "desc2", name: "title", widget: "string" }